DROP TABLE IF EXISTS cells;

DROP TABLE IF EXISTS amoebas;

CREATE TABLE IF NOT EXISTS cells
(
    id BIGSERIAL PRIMARY KEY,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    cAMP_level INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS amoebas
(
    id BIGSERIAL PRIMARY KEY,
    position INTEGER NOT NULL,
    state VARCHAR(100) NOT NULL
    );